Document: ebiff
Title: Debian ebiff Manual
Author: <insert document author here>
Abstract: This manual describes what ebiff is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ebiff/ebiff.sgml.gz

Format: postscript
Files: /usr/share/doc/ebiff/ebiff.ps.gz

Format: text
Files: /usr/share/doc/ebiff/ebiff.text.gz

Format: HTML
Index: /usr/share/doc/ebiff/html/index.html
Files: /usr/share/doc/ebiff/html/*.html

  
