.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EBIFF SECTION "February 28, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ebiff \- program to notify the user when new mail arrives
.SH SYNOPSIS
.B ebiff
.SH DESCRIPTION
\fBebiff\fP is an enhanced and extensible biff clone.
.PP
See /usr/share/doc/ebiff/manual.html for info about the configuration file
.SH OPTIONS
.TP
.B \-f file, \-\-file file
Uses file instead of ~/.ebiff as the configuration file
.br
.TP
.B \-V, \-\-version
Show version of program.
.br
.SH AUTHOR
This manual page was written by Enrico Tassi <gareuselesinge@users.sourceforge.net>,
for the Debian project (but may be used by others).
